# SPDX-License-Identifier: Apache-2.0
name: "ZXCron: [Platform] Main JRS Regression"
on:
  schedule:
    - cron: "30 5 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  trigger-task:
    name: Trigger Daily Run
    runs-on: hiero-network-node-linux-small-scheduler
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Display Branch Information
        run: |
          printf "Ref: \t\t${{ github.ref }}"
          printf "Head Ref: \t\t${{ github.head_ref }}"
          printf "Ref Name: \t${{ github.ref_name }}"
          printf "Commit SHA: \t${{ github.sha }}"
  cron:
    name: Cron
    uses: ./.github/workflows/platform-zxc-launch-jrs-workflow.yaml
    needs:
      - trigger-task
    with:
      ref: ${{ github.sha }}
      branch-name: ${{ github.ref_name }}
      workflow-file: platform-flow-jrs-daily-regression.yaml
      workflow-file-ref: ${{ github.ref }}
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
